#CONFIG PORT
server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: localhost:9092
##    DATASOURCE MARIADB
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/account-service-db?createDatabaseIfNotExist=true&autoReconnect=true&UseUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 1111
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect